### ISSUE TITLE
Etcd block request forever

### ISSUE THREAD

**Issue by snowdreamist** [coreos/etcd#2476]
Related to  #2266 

Hi, guys

I've upgraded etcd to 2.0.4, the 'Internal server error' goes away, but still have the blocking issues.
I'm not sure if anybody else has already created an issue for this problem, here's my service log, nothing new:
    
    Traceback (most recent call last):
      File "/home/p/code/datamiller/paas/lib/python/paas/src/paas/lib/asyncrequests.py", line 77, in __send__
        self.request = self.method(*self.args, **self.kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in get
        return request('get', url, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 49, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
        r.content
      File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 724, in content
        self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
      File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 660, in generate
        raise ConnectionError(e)
    ConnectionError: HTTPConnectionPool(host='192.168.150.11', port=4001): Read timed out.

The timeout is 5s, I believe etcd could complete the write request in 5s among a 5 nodes cluster.
This problem is happened about every 1min regularly, and no related service log could be found.

How can it solve/debug this problem?

* Adjust the timeout seconds ?
* Enable etcd `debug mode` or something like that ?
* ...

By the way, I found some errors in etcd log, but not very related to the problem:
      2015/03/10 13:22:06 sender: error posting to 9ffcb4b4dd84183e: read tcp 192.168.150.11:7001: i/o timeout
      2015/03/10 13:22:06 sender: the connection with 9ffcb4b4dd84183e became inactive
      2015/03/10 13:22:06 sender: the connection with 9ffcb4b4dd84183e became active
This log comes from node 192.168.150.16 and at that time (13:22:06) 192.168.150.11 logs nothing.

So, what should I do next ?

**Comment by AdoHe** [comment]
@snowdreamist can you tell how you setup the cluster? the environment and the configuration?

**Comment by snowdreamist** [comment]
@AdoHe 

Of course. The etcd is started through the command

       /var/lib/etcd/etcd -name etcd0 \
          -discovery-srv m.com \
          -initial-advertise-peer-urls http://etcd0.m.com:7001 \
          -advertise-client-urls http://etcd0.m.com:4001 \
          -initial-cluster-token etcd-prod-cluster \
          -initial-cluster-state new \
          -listen-peer-urls 'http://etcd0.m.com:7001' \
          -listen-client-urls 'http://etcd0.m.com:4001' \
          -data-dir /var/lib/etcd/default.etcd 2>/var/log/etcd.log >&2

I've 5 nodes from etcd0 to etcd4, the same as its sub domain name.
Each node is started by the same code as above except convert etcd0 to etcd[1234]

And I found the following error logs just now:

        2015/03/10 16:35:39 sender: error posting to 4d18ffbde916ed55: dial tcp 192.168.150.9:7001: connection refused
        2015/03/10 16:35:39 sender: the connection with 4d18ffbde916ed55 became inactive
        2015/03/10 16:35:39 rafthttp: encountered error writing to server log stream: write tcp 192.168.150.9:41888: broken pipe
        2015/03/10 16:35:39 rafthttp: server streaming to 4d18ffbde916ed55 at term 20 has been stopped
2015/03/10 16:35:39 stream: error sending message: stopped

Another node:

        2015/03/10 11:27:57 sender: error posting to 9ffcb4b4dd84183e: read tcp 192.168.150.11:7001: i/o timeout
        2015/03/10 11:27:57 sender: the connection with 9ffcb4b4dd84183e became inactive
        2015/03/10 11:27:57 sender: the connection with 9ffcb4b4dd84183e became active
        2015/03/10 11:28:03 etcdhttp: unexpected error: etcdserver: request timed out
        2015/03/10 11:28:03 etcdhttp: unexpected error: etcdserver: request timed out
        2015/03/10 11:28:03 etcdhttp: unexpected error: etcdserver: request timed out
        2015/03/10 11:28:03 etcdhttp: unexpected error: etcdserver: request timed out
        2015/03/10 11:28:03 etcdhttp: unexpected error: etcdserver: request timed out
        2015/03/10 11:28:03 etcdhttp: unexpected error: etcdserver: request timed out
        2015/03/10 11:28:03 etcdhttp: unexpected error: etcdserver: request timed out
        2015/03/10 11:28:03 etcdhttp: unexpected error: etcdserver: request timed out

It seems all of the issues are caused by etcd request timeout.

The hardwares are virtual machines which are running on an IAAS service provider, and the machines ran etcd is somehow not very powerful, just 1GB mem + 1 CPU core. (I think etcd won't eat too many memory or cpu cycles, is it the problem?) The lower layer architecture is quite like openstack. And I'm sure the network is stable, or stable enough.

The os is  Ubuntu 14.04
Linux kernel is 3.13.0-24-generic

If you need more information let me know.

**Comment by yichengq** [comment]
@snowdreamist The lost of message is due to a bug, and we have fixed it: https://github.com/coreos/etcd/commit/59327bab47f75329c609cc81ece0265d9b18b876

Could you check whether the latest https://github.com/coreos/etcd/tree/release-2.0 fix your problem? We will release 2.0.5 based on this tomorrow BTW.

**Comment by kelseyhightower** [comment]
@snowdreamist etcd 2.0.5 has been released, can you retest.

**Comment by snowdreamist** [comment]
Hi, everyone.

I've upgraded to 2.0.5 at this morning, I'm sorry to say that the error is still there.

I've go through all my 5 etcd nodes' log, no error found (Except the error when I'm restarting the cluster node one by one to upgrade from 2.0.4 to 2.0.5): no internal error, no request timeout, not leader lost ...

It's very strange but I found, some of the etcd node will never request time out or rarely time out but some are very often, the time interval between the errors is about 1 min ~ 2 min and request timeout is 5s.

Here's a piece of my service debug log, has removed some unnecessary part:

        2015-03-12 10:40:26,442 - ERROR - asyncrequest - Send request failed
        Traceback (most recent call last):
        ......
        ConnectionError: HTTPConnectionPool(host='192.168.150.16', port=4001): Read timed out.
        2015-03-12 10:40:32,756 - DEBUG - servicekeeper - Start to register @[22] times with [1] register info
        2015-03-12 10:40:52,953 - DEBUG - servicekeeper - Start to register @[23] times with [1] register info
        2015-03-12 10:41:13,455 - DEBUG - servicekeeper - Start to register @[24] times with [1] register info
        2015-03-12 10:41:26,448 - ERROR - asyncrequest - Send request failed
        Traceback (most recent call last):
        ......
        ConnectionError: HTTPConnectionPool(host='192.168.150.16', port=4001): Read timed out.
        2015-03-12 10:41:34,151 - DEBUG - servicekeeper - Start to register @[25] times with [1] register info
        2015-03-12 10:41:54,352 - DEBUG - servicekeeper - Start to register @[26] times with [1] register info
        2015-03-12 10:42:14,551 - DEBUG - servicekeeper - Start to register @[27] times with [1] register info
        2015-03-12 10:42:26,455 - ERROR - asyncrequest - Send request failed
        Traceback (most recent call last):
        ......
        ConnectionError: HTTPConnectionPool(host='192.168.150.16', port=4001): Read timed out.
        2015-03-12 10:42:34,752 - DEBUG - servicekeeper - Start to register @[28] times with [1] register info
        2015-03-12 10:42:54,950 - DEBUG - servicekeeper - Start to register @[29] times with [1] register info
        2015-03-12 10:43:15,150 - DEBUG - servicekeeper - Start to register @[30] times with [1] register info
        2015-03-12 10:43:26,464 - ERROR - asyncrequest - Send request failed
        Traceback (most recent call last):
        ......
        ConnectionError: HTTPConnectionPool(host='192.168.150.16', port=4001): Read timed out.

Each service will register itself every 20s, each register request including three etcd requests:  
* Set value to two different nodes
* Set a directory ttl
The request is sent by requests with gevent for better performance.  
We have 8 service instances in this environment by the way and all of the request payloads are quite small.

What should I do next ?

**Comment by xiang90** [comment]
@snowdreamist 
Great to hear that. We will keep this open for one or two more days. If there is no further issues, I will close it.
