### ISSUE TITLE
Inconsistent 2.1.0 behavior for v2/security

### ISSUE THREAD

**Issue by raoofmd** [coreos/etcd#3099]
I've a 3 member cluster, where discovery is based on dns on https.
In the below sample I'm talking to proxy which is also using the same dns discovery as the cluster.

Last login: Thu Jul  2 19:51:45 2015 from xx.xx.xx.xx
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":true}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":true}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":true}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":true}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":true}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":true}
[rm@dev123 ~]$
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/roles
{"roles":["guest","root","webServicesDevRole"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"users":["root","webServicesDev"]}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ more enableSecurity.json
{"user" : "root", "password": "rm01d3"}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":true}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":true}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":true}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":false}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":true}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":true}
[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/users
{"message":"Insufficient credentials"}[rm@dev123 ~]$ curl --insecure http://test.dev.net:2377/v2/security/enable
{"enabled":true}

**Comment by raoofmd** [comment]
On researching more and trying to talk to the individual client url's of the cluster, I figured out that 2 machines have security enabled and 1 doesn't.
How is this possible?

**Comment by philips** [comment]
This shouldn't be possible with the upgrade process. @yichengq ?

**Comment by yichengq** [comment]
@raoofmd Could you run `etcdctl cluster-health`? Could you share your etcd command line and its log with us? I doubt that the node doesn't work in health.

**Comment by yichengq** [comment]
Moreover, could you try it in 2.1.0-rc? We renamed it to /v2/auth and fixed some auth bugs.

**Comment by raoofmd** [comment]
Seems like the machine which is not in sync isn't a follower.

[rm@dev123 etcd]$
[rm@dev123 etcd]$ curl -u root:m1lkm3 --insecure https://node01.etcd.dev.com:2379/v2/stats/leader
{"leader":"f95caeae097ab105","followers":{"4c5854cca2fdc9c":{"latency":{"current":0.008246,"average":0.008524584690827666,"standardDeviation":0.04678472663385295,"minimum":0.003189,"maximum":16.523989},"counts":{"fail":0,"success":1811424}},"5f97c3330e24a56d":{"latency":{"current":0.216439,"average":0.006946630781092698,"standardDeviation":0.054280255255474696,"minimum":0.003095,"maximum":16.535282},"counts":{"fail":0,"success":1783010}}}}[rm@dev123 etcd]$
[rm@dev123 etcd]$ curl -u root:m1lkm3 --insecure https://node01.etcd.dev.com:2379/v2/stats/self
{"name":"node01","id":"f95caeae097ab105","state":"StateLeader","startTime":"2015-07-01T20:49:43.167312024Z","leaderInfo":{"leader":"f95caeae097ab105","uptime":"86h37m30.471627977s","startTime":"2015-07-03T04:02:22.06739104Z"},"recvAppendRequestCnt":252676,"sendAppendRequestCnt":3594578,"sendPkgRate":9.996253861381367,"sendBandwidthRate":741.7220365144976}[rm@dev123 etcd]$
[rm@dev123 etcd]$ service etcd status
etcd is running (pid is 6792).
[rm@dev123 etcd]$ ps -ef | grep etcd
etcd      6792     1  0 Jul01 ?        01:04:13 /var/lib/etcd/etcd -advertise-client-urls https://node01.etcd.dev.com:2379 -initial-cluster-state new -name node01 -data-dir /var/lib/etcd/cluster/datadir -listen-peer-urls https://node01.etcd.dev.com:2380 -initial-advertise-peer-urls https://node01.etcd.dev.com:2380 -listen-client-urls https://node01.etcd.dev.com:2379 -discovery-srv etcd.dev.com -trusted-ca-file /var/home/rm/ca.cert.pem -cert-file /var/home/rm/node01.etcd.dev.com.cert.pem -key-file /var/home/rm/node01.etcd.dev.com.pem -peer-trusted-ca-file /var/home/rm/ca.cert.pem -peer-cert-file /var/home/rm/node01.etcd.dev.com.cert.pem -peer-key-file /var/home/rm/node01.etcd.dev.com.pem -heartbeat-interval 200 -election-timeout 2000 -initial-cluster-token etcd-cluster-dev
9415      9709     1  0 Jul01 ?        00:02:26 /var/lib/etcdProxy/etcd -data-dir /var/lib/etcdProxy/proxy/datadir -listen-client-urls http://node01.etcd.dev.com:2377 -discovery-srv etcd.dev.com -trusted-ca-file /var/home/rm/ca.cert.pem -cert-file /var/home/rm/node01.etcd.dev.com.cert.pem -key-file /var/home/rm/node01.etcd.dev.com.pem -proxy on
52674    20641 31726  0 18:40 pts/1    00:00:00 grep etcd
[rm@dev123 etcd]$


[rm@dev456 etcd]$  curl -u root:m1lkm3 --insecure https://node02.etcd.dev.com:2379/v2/stats/leader
{"message":"not current leader"}[rm@dev456 etcd]$  curl -u root:m1lkm3 --insecure https://node02.etcd.dev.com:2379/v2/stats/self
{"name":"node02","id":"5f97c3330e24a56d","state":"StateFollower","startTime":"2015-07-01T20:49:43.694940216Z","leaderInfo":{"leader":"f95caeae097ab105","uptime":"86h37m37.6214396s","startTime":"2015-07-03T04:02:22.067833366Z"},"recvAppendRequestCnt":2035193,"recvPkgRate":4.937656417448523,"recvBandwidthRate":367.92946794617677,"sendAppendRequestCnt":0}[rm@dev456 etcd]$
[rm@dev456 etcd]$ service etcd status
etcd is running (pid is 27001).
[rm@dev456 etcd]$ ps -ef | grep etcd
52674    16319 15985  0 18:40 pts/0    00:00:00 grep etcd
etcd     27001     1  0 Jul01 ?        00:50:49 /var/lib/etcd/etcd -advertise-client-urls https://node02.etcd.dev.com:2379 -initial-cluster-state new -name node02 -data-dir /var/lib/etcd/cluster/datadir -listen-peer-urls https://node02.etcd.dev.com:2380 -initial-advertise-peer-urls https://node02.etcd.dev.com:2380 -listen-client-urls https://node02.etcd.dev.com:2379 -discovery-srv etcd.dev.com -trusted-ca-file /var/home/rm/ca.cert.pem -cert-file /var/home/rm/node02.etcd.dev.com.cert.pem -key-file /var/home/rm/node02.etcd.dev.com.pem -peer-trusted-ca-file /var/home/rm/ca.cert.pem -peer-cert-file /var/home/rm/node02.etcd.dev.com.cert.pem -peer-key-file /var/home/rm/node02.etcd.dev.com.pem -heartbeat-interval 200 -election-timeout 2000 -initial-cluster-token etcd-cluster-dev
[rm@dev456 etcd]$


[rm@dev789 etcd]$  curl -u root:m1lkm3 --insecure https://node03.etcd.dev.com:2379/v2/stats/leader
{"message":"not current leader"}[rm@dev789 etcd]$  curl -u root:m1lkm3 --insecure https://node03.etcd.dev.com:2379/v2/stats/self
{"name":"node03","id":"4c5854cca2fdc9c","state":"StateFollower","startTime":"2015-07-01T20:49:44.321450261Z","leaderInfo":{"leader":"f95caeae097ab105","uptime":"86h37m45.28236395s","startTime":"2015-07-03T04:02:22.067546305Z"},"recvAppendRequestCnt":1811547,"recvPkgRate":4.938177655925473,"recvBandwidthRate":367.9683080312866,"sendAppendRequestCnt":504740}[rm@dev789 etcd]$
[rm@dev789 etcd]$ service etcd status
etcd is running (pid is 15271).
[rm@dev789 etcd]$ ps -ef | grep etcd
52674      637 31487  0 18:41 pts/0    00:00:00 grep etcd
etcd     15271     1  0 Jul01 ?        00:36:58 /var/lib/etcd/etcd -advertise-client-urls https://node03.etcd.dev.com:2379 -initial-cluster-state new -name node03 -data-dir /var/lib/etcd/cluster/datadir -listen-peer-urls https://node03.etcd.dev.com:2380 -initial-advertise-peer-urls https://node03.etcd.dev.com:2380 -listen-client-urls https://node03.etcd.dev.com:2379 -discovery-srv etcd.dev.com -trusted-ca-file /var/home/rm/ca.cert.pem -cert-file /var/home/rm/node03.etcd.dev.com.cert.pem -key-file /var/home/rm/node03.etcd.dev.com.pem -peer-trusted-ca-file /var/home/rm/ca.cert.pem -peer-cert-file /var/home/rm/node03.etcd.dev.com.cert.pem -peer-key-file /var/home/rm/node03.etcd.dev.com.pem -heartbeat-interval 200 -election-timeout 2000 -initial-cluster-token etcd-cluster-dev
[rm@dev789 etcd]$

**Comment by raoofmd** [comment]
[rm@dev123 etcd]$
[rm@dev123 etcd]$ curl -u root:pass --insecure https://node01.etcd.dev.com:2379/v2/stats/leader
{"leader":"f95caeae097ab105","followers":{"4c5854cca2fdc9c":{"latency":{"current":0.008246,"average":0.008524584690827666,"standardDeviation":0.04678472663385295,"minimum":0.003189,"maximum":16.523989},"counts":{"fail":0,"success":1811424}},"5f97c3330e24a56d":{"latency":{"current":0.216439,"average":0.006946630781092698,"standardDeviation":0.054280255255474696,"minimum":0.003095,"maximum":16.535282},"counts":{"fail":0,"success":1783010}}}}
[rm@dev123 etcd]$
[rm@dev123 etcd]$ curl -u root:pass --insecure https://node01.etcd.dev.com:2379/v2/stats/self
{"name":"node01","id":"f95caeae097ab105","state":"StateLeader","startTime":"2015-07-01T20:49:43.167312024Z","leaderInfo":{"leader":"f95caeae097ab105","uptime":"86h37m30.471627977s","startTime":"2015-07-03T04:02:22.06739104Z"},"recvAppendRequestCnt":252676,"sendAppendRequestCnt":3594578,"sendPkgRate":9.996253861381367,"sendBandwidthRate":741.7220365144976}
[rm@dev123 etcd]$
[rm@dev123 etcd]$ service etcd status
etcd is running (pid is 6792).
[rm@dev123 etcd]$ ps -ef | grep etcd
etcd      6792     1  0 Jul01 ?        01:04:13 /var/lib/etcd/etcd -advertise-client-urls https://node01.etcd.dev.com:2379 -initial-cluster-state new -name node01 -data-dir /var/lib/etcd/cluster/datadir -listen-peer-urls https://node01.etcd.dev.com:2380 -initial-advertise-peer-urls https://node01.etcd.dev.com:2380 -listen-client-urls https://node01.etcd.dev.com:2379 -discovery-srv etcd.dev.com -trusted-ca-file /var/home/rm/ca.cert.pem -cert-file /var/home/rm/node01.etcd.dev.com.cert.pem -key-file /var/home/rm/node01.etcd.dev.com.pem -peer-trusted-ca-file /var/home/rm/ca.cert.pem -peer-cert-file /var/home/rm/node01.etcd.dev.com.cert.pem -peer-key-file /var/home/rm/node01.etcd.dev.com.pem -heartbeat-interval 200 -election-timeout 2000 -initial-cluster-token etcd-cluster-dev
9415      9709     1  0 Jul01 ?        00:02:26 /var/lib/etcdProxy/etcd -data-dir /var/lib/etcdProxy/proxy/datadir -listen-client-urls http://node01.etcd.dev.com:2377 -discovery-srv etcd.dev.com -trusted-ca-file /var/home/rm/ca.cert.pem -cert-file /var/home/rm/node01.etcd.dev.com.cert.pem -key-file /var/home/rm/node01.etcd.dev.com.pem -proxy on
52674    20641 31726  0 18:40 pts/1    00:00:00 grep etcd
[rm@dev123 etcd]$


[rm@dev456 etcd]$  curl -u root:pass --insecure https://node02.etcd.dev.com:2379/v2/stats/leader
{"message":"not current leader"}[rm@dev456 etcd]$  curl -u root:pass --insecure https://node02.etcd.dev.com:2379/v2/stats/self
{"name":"node02","id":"5f97c3330e24a56d","state":"StateFollower","startTime":"2015-07-01T20:49:43.694940216Z","leaderInfo":{"leader":"f95caeae097ab105","uptime":"86h37m37.6214396s","startTime":"2015-07-03T04:02:22.067833366Z"},"recvAppendRequestCnt":2035193,"recvPkgRate":4.937656417448523,"recvBandwidthRate":367.92946794617677,"sendAppendRequestCnt":0}
[rm@dev456 etcd]$
[rm@dev456 etcd]$ service etcd status
etcd is running (pid is 27001).
[rm@dev456 etcd]$ ps -ef | grep etcd
52674    16319 15985  0 18:40 pts/0    00:00:00 grep etcd
etcd     27001     1  0 Jul01 ?        00:50:49 /var/lib/etcd/etcd -advertise-client-urls https://node02.etcd.dev.com:2379 -initial-cluster-state new -name node02 -data-dir /var/lib/etcd/cluster/datadir -listen-peer-urls https://node02.etcd.dev.com:2380 -initial-advertise-peer-urls https://node02.etcd.dev.com:2380 -listen-client-urls https://node02.etcd.dev.com:2379 -discovery-srv etcd.dev.com -trusted-ca-file /var/home/rm/ca.cert.pem -cert-file /var/home/rm/node02.etcd.dev.com.cert.pem -key-file /var/home/rm/node02.etcd.dev.com.pem -peer-trusted-ca-file /var/home/rm/ca.cert.pem -peer-cert-file /var/home/rm/node02.etcd.dev.com.cert.pem -peer-key-file /var/home/rm/node02.etcd.dev.com.pem -heartbeat-interval 200 -election-timeout 2000 -initial-cluster-token etcd-cluster-dev
[rm@dev456 etcd]$


[rm@dev789 etcd]$  curl -u root:pass --insecure https://node03.etcd.dev.com:2379/v2/stats/leader
{"message":"not current leader"}[rm@dev789 etcd]$  curl -u root:pass --insecure https://node03.etcd.dev.com:2379/v2/stats/self
{"name":"node03","id":"4c5854cca2fdc9c","state":"StateFollower","startTime":"2015-07-01T20:49:44.321450261Z","leaderInfo":{"leader":"f95caeae097ab105","uptime":"86h37m45.28236395s","startTime":"2015-07-03T04:02:22.067546305Z"},"recvAppendRequestCnt":1811547,"recvPkgRate":4.938177655925473,"recvBandwidthRate":367.9683080312866,"sendAppendRequestCnt":504740}
[rm@dev789 etcd]$
[rm@dev789 etcd]$ service etcd status
etcd is running (pid is 15271).
[rm@dev789 etcd]$ ps -ef | grep etcd
52674      637 31487  0 18:41 pts/0    00:00:00 grep etcd
etcd     15271     1  0 Jul01 ?        00:36:58 /var/lib/etcd/etcd -advertise-client-urls https://node03.etcd.dev.com:2379 -initial-cluster-state new -name node03 -data-dir /var/lib/etcd/cluster/datadir -listen-peer-urls https://node03.etcd.dev.com:2380 -initial-advertise-peer-urls https://node03.etcd.dev.com:2380 -listen-client-urls https://node03.etcd.dev.com:2379 -discovery-srv etcd.dev.com -trusted-ca-file /var/home/rm/ca.cert.pem -cert-file /var/home/rm/node03.etcd.dev.com.cert.pem -key-file /var/home/rm/node03.etcd.dev.com.pem -peer-trusted-ca-file /var/home/rm/ca.cert.pem -peer-cert-file /var/home/rm/node03.etcd.dev.com.cert.pem -peer-key-file /var/home/rm/node03.etcd.dev.com.pem -heartbeat-interval 200 -election-timeout 2000 -initial-cluster-token etcd-cluster-dev
[rm@dev789 etcd]$

**Comment by raoofmd** [comment]
[rmohammed@tomcat-fe-vm-01 ~]$  curl -u root:m1lkm3 --insecure https://tomcat-fe-vm-01.dloco.s.vonagenetworks.net:2379/v2/members
{"members":[{"id":"4c5854cca2fdc9c","name":"node03","peerURLs":["https://node03.etcd.vonagedev.com:2380"],"clientURLs":["https://node03.etcd.vonagedev.com:2379"]},{"id":"5f97c3330e24a56d","name":"node02","peerURLs":["https://node02.etcd.vonagedev.com:2380"],"clientURLs":["https://node02.etcd.vonagedev.com:2379"]},{"id":"f95caeae097ab105","name":"node01","peerURLs":["https://node01.etcd.vonagedev.com:2380"],"clientURLs":["https://node01.etcd.vonagedev.com:2379"]}]}
[rmohammed@tomcat-fe-vm-01 ~]$

**Comment by raoofmd** [comment]
[rm@dev789 etcd]$  curl -u root:m1lkm3 --insecure https://node02.etcd.dev.com:2379/v2/members
{"members":[{"id":"4c5854cca2fdc9c","name":"node03","peerURLs":["https://node03.etcd.dev.com:2380"],"clientURLs":["https://node03.etcd.dev.com:2379"]},{"id":"5f97c3330e24a56d","name":"node02","peerURLs":["https://node02.etcd.dev.com:2380"],"clientURLs":["https://node02.etcd.dev.com:2379"]},{"id":"f95caeae097ab105","name":"node01","peerURLs":["https://node01.etcd.dev.com:2380"],"clientURLs":["https://node01.etcd.dev.com:2379"]}]}

**Comment by raoofmd** [comment]
[rm@dev789 etcd]$  curl -u root:pass --insecure https://node02.etcd.dev.com:2379/v2/members
{"members":[{"id":"4c5854cca2fdc9c","name":"node03","peerURLs":["https://node03.etcd.dev.com:2380"],"clientURLs":["https://node03.etcd.dev.com:2379"]},{"id":"5f97c3330e24a56d","name":"node02","peerURLs":["https://node02.etcd.dev.com:2380"],"clientURLs":["https://node02.etcd.dev.com:2379"]},{"id":"f95caeae097ab105","name":"node01","peerURLs":["https://node01.etcd.dev.com:2380"],"clientURLs":["https://node01.etcd.dev.com:2379"]}]}

**Comment by raoofmd** [comment]
May be I dont understand this, why is member/leader api is not showing any issue but this one is unhealthy.
[rm@dev456 etcd]$ ETCDCTL_PEERS="https://node01.etcd.dev.com:2379,https://node02.etcd.dev.com:2379,https://node03.etcd.dev.com:2379" ./etcdctl cluster-health
cluster is unhealthy

If I run /v2/members on all 3 machines I'm getting proper response

By documentation on cluster-health, I understand that this first gets the leader and then gets the individual advertised client URLs and verifies the URLs to get the state of the cluster.
Isn't it enough that I'm individually hitting the v2/members on client URLs to verify that the health is ok.

**Comment by yichengq** [comment]
> Isn't it enough that I'm individually hitting the v2/members on client URLs to verify that the health is ok.

Yes, this only indicates that this etcd member is working. An healthy cluster indicates that most of members could synchronize with others. `etcdctl cluster-health` tells that your cluster is unhealthy. Could you provide etcd process stdout&stderr for us to dig in?

**Comment by raoofmd** [comment]
@yichengq Please find the logs below

https://gist.github.com/raoofmd/2392865f66573f54b1e2

Another question is how to come out of this state and make the cluster healthy (just restarting will do)

**Comment by yichengq** [comment]
The cluster seems healthy, and `etcdctl cluster-health` gave some false warning. After reading through the log, it comes out that you are using an old version that auth feature was developed, and we have fixed a lot of problems about it since then(https://github.com/coreos/etcd/pull/2654 should have fixed the problem you met). Could you download 2.1.0-rc.0 and give it a try?

**Comment by raoofmd** [comment]
@yichengq 
I'll update etcd to 2.1.0-rc.0 but I'm still not sure why does it say unhealthy and will updating to rc will resolve the state issue.
I have another cluster of 5 machines and it says the state as unhealthy as well, whereas the individual members/logs seems fine.

Is it an issue with etcdctl cluster-health

**Comment by yichengq** [comment]
I am unsure about `etcdctl cluster-health` problem. It helps a lot if you could try 2.1.0-rc version etcdctl for it.

When I went through your workflow, it printed out error syncing cluster instead of unhealthy. Did you set key/cert files for etcdctl?

**Comment by raoofmd** [comment]
Ok I'm in the process of upgrading. Will let you know.
I didnt set certs for etcdctl. Did for peers/client

**Comment by raoofmd** [comment]
@yichengq 
Will a data directory of 2.1.0.alpha, in this case the unhealthy cluster's data directory be used with the 2.1.0.rc 
- cluster unhealthy
- v2/security changed to v2/auth

**Comment by yichengq** [comment]
Maybe not for auth feature. We changed its logic a little bit, and it has different workflow now. Try to start with a empty data dir and document here: https://github.com/coreos/etcd/blob/master/Documentation/auth_api.md#example-workflow

We have also implemented auth feature in etcdctl, though it has not been documented yet.

**Comment by raoofmd** [comment]
@yichengq
I upgraded and it works fine. Cluster shows healthy and the auth feature seems to work great as well. logging in this version makes a lot more sense.

But the question remains... what if the cluster goes unhealthy in production, will restarting fix the issue and sync up the nodes - which I dont think so

**Comment by xiang90** [comment]
@raoofmd 
Closing since the original issue is solved.
Can you open up another issue for your another question? So other people can also see it. Thanks.

**Comment by raoofmd** [comment]
@yichengq Thanks

**Comment by raoofmd** [comment]
@yichengq again the same issue

Though the cluster seems to work fine but the etcdctl returns unhealthy response.

**Comment by yichengq** [comment]
@raoofmd Could you open an new issue for it with more details? It is easier for us to follow and discuss.
