### ISSUE TITLE
Etcd2 watcher (sometimes) keep getting old events

### ISSUE THREAD

**Issue by ederuiter** [coreos/etcd#6742]
I have run into some hard to debug problems with etcd. A couple of times a day some of our services which are using etcd will go into a almost infinite loop. 
I have traced it down to a watcher that goes wild .. as it goes wild, it will repeatedly get old events. So much that both the server and the client will eat all CPU available to them. The weird thing is that after a while the problem seems to go away.  

I have been able to reproduce this on a test machine (single node etcd cluster, running on coreos 1122.3.0). Before any of our services started I ran an etcdctl watcher in the background so I was able to capture the output of the watcher. 

`etcdctl --debug -o json  watch --recursive --forever /ha`

After all of the services were stopped again I still kept getting events from the etcdctl watch command: 

```
[set] /ha/prometheus/services/1
{"action":"set","node":{"key":"/ha/prometheus/services/1","value":"1","nodes":null,"createdIndex":164124,"modifiedIndex":164124},"prevNode":{"key":"/ha/prometheus/services/1","value":"1","nodes":null,"createdIndex":163241,"modifiedIndex":163241}}
cURL Command: curl -X GET http://10.0.12.1:2379/v2/keys/ha?recursive=true&wait=true&waitIndex=164125
[set] /ha/prometheus/services/1
{"action":"set","node":{"key":"/ha/prometheus/services/1","value":"1","nodes":null,"createdIndex":164124,"modifiedIndex":164124},"prevNode":{"key":"/ha/prometheus/services/1","value":"1","nodes":null,"createdIndex":163241,"modifiedIndex":163241}}
cURL Command: curl -X GET http://10.0.12.1:2379/v2/keys/ha?recursive=true&wait=true&waitIndex=164125
```

This kept repeating for a long long time ..
After stopping etcdctl and restarting the command it wouldn't give me any event.
But with the after-index parameter I was able to reproduce it afterwards (only for a short time)

`etcdctl --debug -o json  watch --recursive --after-index "163822" --forever /ha > watch.txt`

```
start to sync cluster using endpoints(http://127.0.0.1:2379,http://127.0.0.1:4001)
cURL Command: curl -X GET http://127.0.0.1:2379/v2/members
got endpoints(http://10.0.12.1:2379) after sync
Cluster-Endpoints: http://10.0.12.1:2379
cURL Command: curl -X GET http://10.0.12.1:2379/v2/keys/ha?recursive=true&wait=true&waitIndex=163823
cURL Command: curl -X GET http://10.0.12.1:2379/v2/keys/ha?recursive=true&wait=true&waitIndex=163211
cURL Command: curl -X GET http://10.0.12.1:2379/v2/keys/ha?recursive=true&wait=true&waitIndex=164125
cURL Command: curl -X GET http://10.0.12.1:2379/v2/keys/ha?recursive=true&wait=true&waitIndex=163836
cURL Command: curl -X GET http://10.0.12.1:2379/v2/keys/ha?recursive=true&wait=true&waitIndex=163211
cURL Command: curl -X GET http://10.0.12.1:2379/v2/keys/ha?recursive=true&wait=true&waitIndex=164125
cURL Command: curl -X GET http://10.0.12.1:2379/v2/keys/ha?recursive=true&wait=true&waitIndex=163836
```

The interesting part here is the waitIndex parameter that etcdctl is suggesting to use, it is cycling between 3 values, and all of them are smaller then the specified after index parameter.

The etcd workload of the services is pretty simple, upon startup they register a key with a ttl of 30 seconds  and every 10 seconds the ttl is updated. Furthermore each service has 2 watches on directories to see if another service has come online. And upon stopping the service the key is removed. 
Each service has it's own directory in etcd. 

The issue can be replicated on the test machine (most of the time) by starting / stopping 3-5 of those services at the same time.

```
etcdctl version 2.3.2
etcd Version: 2.3.2
Git SHA: ce63f10
Go Version: go1.5.4
Go OS/Arch: linux/amd64
```

**Comment by xiang90** [comment]
@ederuiter 

Hi, can you provide me a simple go program that I can run against a local etcd cluster to reproduce the issue you described? It would dramatically accelerate the speed to resolve this issue.

Thanks!

**Comment by ederuiter** [comment]
@xiang90 
With this simple test program I am able to trigger it pretty reliable on my test machine: https://gist.github.com/ederuiter/39ea71b16274eaae5facf41aa270fbac 
The test.sh runner script accepts a single parameter specifying the number of programs to spawn, with 1 it seems almost impossible to trigger it (I have seen it once) with 2 I can reproduce is almost every time.

The test program is quite simple, it sets a single key with a default ttl of 30 seconds, and every 10 seconds key is refreshed. Besides that it has a recursive watch on the same directory as the key.
The runner script starts each test program with it's own directory (/test/test<index>)

**Comment by xiang90** [comment]
I noticed you used the refresh feature. This should be fixed by https://github.com/coreos/etcd/commit/3b100ad142271c37b095732a27876eafec5f8be3.

Can you upgrade your etcd cluster to 2.3.7? Then the problem should go away. Thanks.

**Comment by ederuiter** [comment]
I tested it with a normal set instead of a refresh, and with that the issue is still present. So I don't think the commit you mentioned will fix it, but when I have the time I will retest it with etcd 2.3.7

**Comment by xiang90** [comment]
@ederuiter Did you test with a fresh etcd setup every time?

**Comment by xiang90** [comment]
Also how long should I expect your script to reproduce the issue?

**Comment by ederuiter** [comment]
Hmm when testing with a fresh etcd setup I was unable to reproduce the issue on 2.3.2 as well as on 2.3.7 (both with and without the refresh). 
On my test and production machines the issue arises directly after starting the test runner.
When I have some more time I can try to import a backup and/or running 2.3.7 on a copy of the datadir of my test machine.

**Comment by xiang90** [comment]
@ederuiter If you use the "refresh" feature, it might make etcd into a broken state that cannot be easily fixed. That is why you can reproduce on your already broken cluster. 

A lot of users and applications depend on watch features, none of them reported this issue after 2.3.3. So I am 99% sure it is the root cause. Let us know if you still find this a problem with a refresh 2.3.7 cluster.

Thanks!

**Comment by ederuiter** [comment]
Indeed, after updating the cluster to 2.3.7 I was unable to reproduce this issue.
