### ISSUE TITLE
spike in ETCD IO: raft apply, peer traffic

### ISSUE THREAD

**Issue by armstrongli** [coreos/etcd#7981]
We got peer traffic spike in ETCD cluster:
<img width="1430" alt="screen shot 2017-05-25 at 1 24 31 am" src="https://cloud.githubusercontent.com/assets/8025018/26416574/f2fa7ada-40e8-11e7-88e1-1851ac5e0dc0.png">

<img width="1428" alt="screen shot 2017-05-25 at 1 14 02 am" src="https://cloud.githubusercontent.com/assets/8025018/26416167/8c034236-40e7-11e7-9b04-0a999afe95b1.png">

After reviewing all the logs of the ETCD members, I didn't find out any abnormal logs.

The guess of this situation is that:
 - All(most of) ETCD followers' raft logs are different from leader's
 - ETCD leader is sending whole data to all ETCD followers

The data transferred is about 500MB.

 - All the members are using SSD
 - All the members are running in the same network
 - All the servers' time is synced
 - No leader election. 
 - No client traffic drops
 - No DB size spike
 - No memory spike

Every ETCD server has 10 CPUs, and 20GB memory.

**Comment by gyuho** [comment]
Do you have server logs during that spikes? That would be helpful for us to debug. Thanks!

**Comment by armstrongli** [comment]
@gyuho I guess there must be something wrong with the storage side. 
we have encountered such issues:
 - raft sync, but data different
 - sudden memory increase until OOM killed
 - raft spike without any signs

**Comment by gyuho** [comment]
@armstrongli What's the etcd version? There was memory leak issue, if you use etcd <3.1.4.

https://github.com/coreos/etcd/blob/master/NEWS#L7

**Comment by armstrongli** [comment]
Yes. it's < 3.1.4

**Comment by xiang90** [comment]
It seems there are a lot of raft proposals received around 06:46. So leader sent out more data to followers. that is expected. RPC is not increased, but it only tracks v3 rpc. Probably you have v2 application? Please always provide server logs of ALL members.

**Comment by armstrongli** [comment]
> Probably you have v2 application? 

All the ETCD members are V3

**Comment by xinxiaogang** [comment]
@xiang90 what is the `raft proposal` exact meaning?

**Comment by xinxiaogang** [comment]
@xiang90 Also, in the presented dashboard, there is also `Disk sync duration` spike along with `Peer traffic` spike. So all these caused by `Raft proposal` spike?
Another questions, will this `Disk sync duration` spike cause leader election and leader change?

**Comment by xinxiaogang** [comment]
I am in the same organization with @armstrongli , for now, we see two major issues with our ETCD cluster:
1. The `Peer traffic` spike happens randomly like presented by @armstrongli 
2. Frequently leader change as below
![image](https://cloud.githubusercontent.com/assets/11433689/26449682/213e66de-4186-11e7-9e3b-0a744c03855f.png)
We are not sure whether these two issues are related or not.

**Comment by armstrongli** [comment]
@xiang90 The leader logs and member logs :

[etcd.log.2017-05-23.22.leader.tar.gz](https://github.com/coreos/etcd/files/1030691/etcd.log.2017-05-23.22.leader.tar.gz)
[etcd.log.2017-05-23.22.member.tar.gz](https://github.com/coreos/etcd/files/1030693/etcd.log.2017-05-23.22.member.tar.gz)

**Comment by xiang90** [comment]
@armstrongli I need the log that corresponds to the graph. The log you provided are from 22:00 to 23:00. Please provide useful information. It is really hard for me to understand what you want and to interpret the data you provided. It is a waste of time for both side if the information is not accurate.

**Comment by armstrongli** [comment]
The graph is in Beijing time. And the log is in UTC time.

**Comment by xiang90** [comment]
@armstrongli Can you please convert the timestamp so that they matches?

**Comment by mitake** [comment]
Hi @armstrongli @xinxiaogang 

I'm still not sure about your case, but in some extreme cases, etcd's batched append strategy would be able to cause high spikes. It is because etcd batches proposals (almost equal to requests from clients) into a single AppendEntries(). This strategy improves both of throughput and latency significantly for ordinary workloads. However, I think that the strategy can make too large delay if the number of proposal in an interval is extremely large because current etcd doesn't provide a parameter for tuning the batching strategy. But please note that I'm not sure about the problem. I've never seen problems like your case.

https://github.com/mitake/etcd/tree/batch-append-limit in this branch you can find a new option `--batch-append` that takes a single integer as its argument. The number corresponds to the limit of the batched entries. I'm glad if you can try it in your environment and report the result.

@xiang90 how do you think about monitoring the numbers of appended entries? I can work on it.

**Comment by xiang90** [comment]
@armstrongli 

I can confirm trom the log, there was no snapshot transfer or election happened. There is a proposal spike which caused the io spike as I mentioned. 

Do you enable auth for the cluster?

**Comment by xiang90** [comment]
@mitake 

If you look at the RPC rate, it is actually very low. 80 rpcs per seconds. but the proposal rate is high. I am wondering if auth retry causes that.

**Comment by mitake** [comment]
@xiang90 ah yes, rpc rate isn't high at all, I missed it. I'll also check the auth retry.

**Comment by xiang90** [comment]
@mitake Yea... The 80k pending proposal is just crazy. I do not know what triggered it.

**Comment by xiang90** [comment]
@mitake I believe they run etcd 3.0.15. I remember we fixed something auth retry related? /cc @heyitsanthony

**Comment by mitake** [comment]
@xiang90 39e9b1f75ac6598c4d0ceebb98a8981fa1c2ce98 would be the change? I looked at it but I'm still not sure it can produce the large pending proposal yet.

**Comment by armstrongli** [comment]
@xiang90 
> Do you enable auth for the cluster?

No. The auth is not enabled.
cc @mitake @heyitsanthony

**Comment by xiang90** [comment]
@armstrongli Not sure what was going on then. Something was hitting etcdv2 api pretty hard is my best guess.

**Comment by armstrongli** [comment]
There're no application reaching etcd except kube-apiserver. And all the apiservers are using `--storage-backend=etcd3` . 
@xiang90 Is there any tool/metrics to catch/show the requests from v2?

**Comment by armstrongli** [comment]
@xiang90 @mitake 
our ETCD cluster goes crazy for almost 1 hour without any sign of stop:

![screen shot 2017-05-26 at 7 20 05 pm](https://cloud.githubusercontent.com/assets/8025018/26492798/a473fb32-4248-11e7-8311-f1a43d25331f.png)

Now it's not one spike anymore.

**Comment by xinxiaogang** [comment]
@mitake we have 200 nodes, 3000 pods, etc.

**Comment by xinxiaogang** [comment]
@mitake @xiang90 From our monitoring, the client traffic reaches around 10+Mbps for each ETCD node.

**Comment by xinxiaogang** [comment]
So from the dashboard, etcd node keeps doing proposal during that time with large entry commit. How can we know where these proposal from?

**Comment by xiang90** [comment]
> So from the dashboard, etcd node keeps doing proposal during that time with large entry commit. How can we know where these proposal from?

monitor you applications. etcd does not support audit at the moment.

**Comment by xiang90** [comment]
> @xiang90 Is there any tool/metrics to catch/show the requests from v2?

cURL etcd at {endpoint}/metrics. there will be some v2 related metrics: 

https://github.com/coreos/etcd/blob/master/Documentation/v2/metrics.md#http-requests

One thing to notice is that the dashboard setup might be incorrect too. So the actual RPC rate might not be what you showed us on the dashboard. We are not sure what really happened still.

**Comment by xinxiaogang** [comment]
> monitor you applications. etcd does not support audit at the moment.
Monitor for what metrics of my application? The application talking to etcd is kube-apiserver. We have do audit of our apiserver request, it is normal as usual.

**Comment by xiang90** [comment]
@xinxiaogang You need to monitor what requests your application sent to etcd, the dababase. not what requests your application received. that part has nothing to do with etcd directly. I have no idea where these proposal coming from. etcd will not generate proposals out of nothing...

again, i am also not sure if the graph you guys provided are accurate. that is something you have to figure out.

we do not really have enough data to help you.

**Comment by xinxiaogang** [comment]
@xiang90 Is there a way or metrics I can get from etcd of the incoming requests from application? I know etcd peers also use http to communicate, how to exclude the peer talk while only leave the application call?

**Comment by xiang90** [comment]
@xinxiaogang 

as i mentioned above, you should read https://github.com/coreos/etcd/blob/master/Documentation/v2/metrics.md#http-requests. 

> These metrics describe the serving of requests (non-watch events) served by etcd members in non-proxy mode: total incoming requests, request failures and processing latency (inc. raft rounds for storage). They are useful for tracking user-generated traffic hitting the etcd cluster .

it answers your question.

**Comment by xiang90** [comment]
for v3 metrics, read the doc here https://github.com/coreos/etcd/blob/master/Documentation/metrics.md

**Comment by xinxiaogang** [comment]
We are running out etcd on v3, so we should get the v3 metrics, correct?

**Comment by xinxiaogang** [comment]
There is only method GET in the metrics? 
```
# HELP etcd_http_received_total Counter of requests received into the system (successfully parsed and authd).
# TYPE etcd_http_received_total counter
etcd_http_received_total{method="GET"} 1
```

**Comment by xiang90** [comment]
@xinxiaogang can you paste all the metrics to here?

**Comment by xiang90** [comment]
of all your servers

**Comment by xinxiaogang** [comment]
[metrics1.txt](https://github.com/coreos/etcd/files/1033223/metrics1.txt)
[metrics2.txt](https://github.com/coreos/etcd/files/1033224/metrics2.txt)
[metrics3.txt](https://github.com/coreos/etcd/files/1033225/metrics3.txt)
[metrics4.txt](https://github.com/coreos/etcd/files/1033226/metrics4.txt)
[metrics5.txt](https://github.com/coreos/etcd/files/1033227/metrics5.txt)

**Comment by xiang90** [comment]
we reproduced this on our own testing k8s cluster. check https://github.com/coreos/etcd/issues/8096. closing this since it is unhelpful.
