### ISSUE TITLE
raft memory leak on etcd v1.4

### ISSUE THREAD

**Issue by jonsyu1** [coreos/etcd#8076]
We're running my [fork of etcd v1.4](https://github.com/jonsyu1/etcd/releases/tag/v3.1.4-palantir) with https://github.com/coreos/etcd/pull/7574 cherry-picked on v3.1.4 and had etcd use up all available >60GB of memory and OOM 6 times in the last 24 hours. Here's the top10 from the heap profile we took just before it panicked from running out of memory.

```
(pprof) top10
538.93MB of 562.15MB total (95.87%)
Dropped 773 nodes (cum <= 2.81MB)
Showing top 10 nodes out of 58 (cum >= 4.51MB)
      flat  flat%   sum%        cum   cum%
  505.78MB 89.97% 89.97%   505.78MB 89.97%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/mvccpb.(*KeyValue).Unmarshal
   13.99MB  2.49% 92.46%    13.99MB  2.49%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb.(*InternalRaftRequest).Marshal
    4.93MB  0.88% 93.34%     7.39MB  1.31%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/rafthttp.startPeer
    4.50MB   0.8% 94.14%     4.50MB   0.8%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raftpb.(*Entry).Unmarshal
       4MB  0.71% 94.85%        4MB  0.71%  runtime.malg
    2.31MB  0.41% 95.26%     6.82MB  1.21%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/rafthttp.(*streamReader).decodeLoop
    2.31MB  0.41% 95.67%     4.78MB  0.85%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/rafthttp.(*streamWriter).run
    0.60MB  0.11% 95.78%   505.38MB 89.90%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.(*store).rangeKeys
    0.50MB 0.089% 95.87%     3.50MB  0.62%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.(*store).restore
         0     0% 95.87%     4.51MB   0.8%  crypto/tls.(*Conn).Handshake
```

It looks like the memory used for unmarshaling `mvccpb.(*KeyValue)` isn't being reclaimed by golang GC.

**Comment by heyitsanthony** [comment]
Try >=3.1.5? This may have been fixed by e1567469597cb8612d2d5ddd7f1c398a7870ef6d

**Comment by jonsyu1** [comment]
Yes, we have cherrypicked e156746 (#7574) and are still experiencing this issue.

**Comment by heyitsanthony** [comment]
@jonsyu1 is there a simple example that can reproduce this issue?

**Comment by jonsyu1** [comment]
Unfortunately, I have not been able to reproduce this outside of production.

**Comment by heyitsanthony** [comment]
How big is the backend / what does `ETCDCTL_API=3 etcdctl -w table endpoint status` give? I'm asking because you're running with a patch that disables quotas entirely (https://github.com/jonsyu1/etcd/commit/8ba4155339d3c08f9667e7ea85115a84b318b251) which could potentially lead to things breaking...

**Comment by jonsyu1** [comment]
```
+------------------------------------------------------+--------------+----------------+---------+-----------+-----------+------------+
|                       ENDPOINT                       |      ID      |    VERSION     | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+------------------------------------------------------+--------------+----------------+---------+-----------+-----------+------------+
| **************************************************** | 5c653cf86e01 | 3.1.4-palantir | 2.3 GB  | true      |    391424 | 1782521207 |
+------------------------------------------------------+--------------+----------------+---------+-----------+-----------+------------+
```
I assume it doesn't matter when I run this command. I can rerun this when etcd memory usage is at its peak if that helps.

**Comment by heyitsanthony** [comment]
@jonsyu1 clients may be submitting Range calls that are grabbing a lot of keys at once (e.g., 60 concurrent clients grabbing 1GB of data each). 3.2 has support for tracing through `/debug/events` and `debug/requests` which might shed some light on this. Postscript output from pprof with the allocation graph would also be helpful for debugging this.

**Comment by jonsyu1** [comment]
We do get warnings against queries with large range/delete range, but most of these reads are of a single key with an order of magnitude of 100KB or less:
```
2017-06-09 18:05:13.686757 W | etcdmain: found invalid file/dir .ready under data dir ************************************************************************* (Ignore this if you are upgrading etcd)
2017-06-09 18:18:44.105293 W | wal: sync duration of 1.155925981s, expected less than 1s
2017-06-09 18:19:44.231543 W | wal: sync duration of 1.762391106s, expected less than 1s
2017-06-09 18:21:43.393311 W | etcdserver: apply entries took too long [743.622585ms for 1 entries]
2017-06-09 18:21:43.393366 W | etcdserver: avoid queries with large range/delete range!
2017-06-09 18:22:44.461063 W | etcdserver: apply entries took too long [781.25976ms for 1 entries]
2017-06-09 18:22:44.461096 W | etcdserver: avoid queries with large range/delete range!
2017-06-09 18:24:44.783154 W | etcdserver: apply entries took too long [220.647556ms for 2 entries]
2017-06-09 18:24:44.783206 W | etcdserver: avoid queries with large range/delete range!
2017-06-09 18:25:45.494834 W | wal: sync duration of 2.219248466s, expected less than 1s
2017-06-09 18:27:44.479440 W | etcdserver: apply entries took too long [606.556047ms for 2 entries]
2017-06-09 18:27:44.479483 W | etcdserver: avoid queries with large range/delete range!
2017-06-09 18:30:46.527246 W | etcdserver: apply entries took too long [1.568174645s for 2 entries]
2017-06-09 18:30:46.527277 W | etcdserver: avoid queries with large range/delete range!
2017-06-09 18:38:46.191177 W | wal: sync duration of 1.825485128s, expected less than 1s
2017-06-09 18:43:46.588006 W | wal: sync duration of 1.910838947s, expected less than 1s
2017-06-09 18:44:46.660078 W | wal: sync duration of 1.863483024s, expected less than 1s
2017-06-09 18:45:47.380423 W | etcdserver: apply entries took too long [1.247984885s for 1 entries]
2017-06-09 18:45:47.380465 W | etcdserver: avoid queries with large range/delete range!
2017-06-09 18:47:47.084887 W | wal: sync duration of 1.530938948s, expected less than 1s
2017-06-09 18:48:47.093548 W | wal: sync duration of 1.749119622s, expected less than 1s
2017-06-09 18:50:47.516170 W | wal: sync duration of 1.540378486s, expected less than 1s
2017-06-09 18:50:47.532672 W | etcdserver: apply entries took too long [1.962938203s for 2 entries]
2017-06-09 18:50:47.532699 W | etcdserver: avoid queries with large range/delete range!
2017-06-09 19:00:45.484449 W | wal: sync duration of 3.298247088s, expected less than 1s
```

Here's the allocation graph: [profile001.pdf](https://github.com/coreos/etcd/files/1065186/profile001.pdf)

**Comment by heyitsanthony** [comment]
OK, it's all coming from `Range`. Are there any Range calls accessing a prefix or a key range with a lot of keys?

**Comment by xiang90** [comment]
> Even if we did make that large prefix read, I don't expect etcd to allocate that much memory to serve the request (or continue to hold onto it). On one host with 220+GB of memory, etcd wound up taking up all of it.

As we already have a guess. Can you try to reproduce it? It is def a bug if etcd used up all 220+GB of memory.

**Comment by jonsyu1** [comment]
OK, I'll try to reproduce this after I adjust our prefix calls. I'll probably have an update for you next week. Thanks for your help!

**Comment by xiang90** [comment]
@jonsyu1 Also the data you showed is simply how much data etcd allocated and where they are allocated. it is not a view of the active memory usage. maybe the memory used to unmarshal data is all released.

**Comment by jonsyu1** [comment]
I agree that the memory allocated in the heap profile may have been released since allocation. What makes me think it's still being leaked is the amount of memory etcd eventually takes up; so I thought it would be helpful to provide what was being allocated. You're right that it may be the smaller allocations adding up over time, but we saw etcd go from 2GB to 60+GB in minutes, so I'm guessing it's the spikes in allocations.

**Comment by xiang90** [comment]
@jonsyu1 Yea. Maybe. I am not sure unless we can get a reproduce.

**Comment by xiang90** [comment]
@jonsyu1 kindly ping.

**Comment by xiang90** [comment]
Low activity. Closing. Reopen if the problem still exists.
