### ISSUE TITLE
add member send database snapshot fail

### ISSUE THREAD

**Issue by yanlinly** [coreos/etcd#8077]
etcd 3.1.1   add member to my cluster , failed.
```
$./etcdctl member add 011130096032 http://11.130.96.32:2280
Added member named 011130096032 with ID d0978fda499ab053 to cluster

ETCD_NAME="011130096032"
ETCD_INITIAL_CLUSTER="010185195037=http://10.185.195.37:2280,011130096032=http://11.130.96.32:2280"
ETCD_INITIAL_CLUSTER_STATE="existing"
```

then master node trace:
```
2017-06-11 21:13:40.635954 I | rafthttp: start to send database snapshot [index: 28930861, to d0978fda499ab053]...
2017-06-11 21:13:40.639252 W | rafthttp: database snapshot [index: 28930861, to: d0978fda499ab053] failed to be sent out (unexpected http status Bad Request while posting to "http://11.130.96.32:2280/raft/snapshot")
2017-06-11 21:13:44.973126 E | etcdserver: publish error: etcdserver: request timed out, possibly due to connection lost
2017-06-11 21:14:10.668344 I | rafthttp: start to send database snapshot [index: 28930861, to d0978fda499ab053]...
2017-06-11 21:14:10.671389 W | rafthttp: database snapshot [index: 28930861, to: d0978fda499ab053] failed to be sent out (unexpected http status Bad Request while posting to "http://11.130.96.32:2280/raft/snapshot")
```
and spend a lot memory
```
$free -g
             total       used       free     shared    buffers     cached
Mem:            32         19         12          0          0          0
-/+ buffers/cache:         18         13
Swap:            1          0          1
```

add node trace:
```
2017-06-11 21:12:29.965644 I | raft: d0978fda499ab053 [term: 1] received a MsgHeartbeat message with higher term from 5c9659641a01 [term: 1364]
2017-06-11 21:12:29.965673 I | raft: d0978fda499ab053 became follower at term 1364
2017-06-11 21:12:29.965687 I | raft: raft.node: d0978fda499ab053 elected leader 5c9659641a01 at term 1364
2017-06-11 21:12:41.306320 E | rafthttp: failed to decode raft message (rafthttp: error limit exceeded)
2017-06-11 21:13:10.270462 E | rafthttp: failed to decode raft message (rafthttp: error limit exceeded)
2017-06-11 21:13:31.271278 E | etcdserver: publish error: etcdserver: request timed out, possibly due to previous leader failure
2017-06-11 21:13:40.637060 E | rafthttp: failed to decode raft message (rafthttp: error limit exceeded)
2017-06-11 21:14:10.668816 E | rafthttp: failed to decode raft message (rafthttp: error limit exceeded)
2017-06-11 21:14:36.271395 E | etcdserver: publish error: etcdserver: request timed out
2017-06-11 21:14:40.408543 E | rafthttp: failed to decode raft message (rafthttp: error limit exceeded)
2017-06-11 21:15:10.625618 E | rafthttp: failed to decode raft message (rafthttp: error limit exceeded)
```

**Comment by xiang90** [comment]
this is fixed by 3.1.9. Update your etcd version should this. thank you.

**Comment by yanlinly** [comment]
v3.2.0  this problem still exist

add node 
etcdserver: publish error: etcdserver: request timed out
2017-07-11 21:01:41.591426 W | rafthttp: health check for peer ac53a1e5678d121a could not connect: dial tcp 10.176.111.237:2280: getsockopt: connection refused
2017-07-11 21:01:44.640781 E | rafthttp: failed to decode raft message (read tcp 11.131.105.212:2280->10.176.111.232:33729: i/o timeout)

master
2017-07-11 20:55:31.336869 W | rafthttp: health check for peer 97ce2299e37ebb20 could not connect: dial tcp 11.131.105.212:2280: getsockopt: connection refused
2017-07-11 20:55:31.590180 I | rafthttp: peer 97ce2299e37ebb20 became active
2017-07-11 20:55:31.590581 I | rafthttp: established a TCP streaming connection with peer 97ce2299e37ebb20 (stream Message writer)
2017-07-11 20:55:31.590695 I | rafthttp: established a TCP streaming connection with peer 97ce2299e37ebb20 (stream MsgApp v2 writer)
2017-07-11 20:55:31.591680 I | rafthttp: established a TCP streaming connection with peer 97ce2299e37ebb20 (stream MsgApp v2 reader)
2017-07-11 20:55:31.591889 I | rafthttp: established a TCP streaming connection with peer 97ce2299e37ebb20 (stream Message reader)
2017-07-11 20:56:01.838821 I | etcdserver/api/v3rpc: grpc: Server.processUnaryRPC failed to write status: stream error: code = DeadlineExceeded desc = "context deadline exceeded"
2017-07-11 20:56:10.904201 I | etcdserver/api/v3rpc: grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
2017-07-11 20:56:19.335907 I | rafthttp: start to send database snapshot [index: 219988768, to 97ce2299e37ebb20]...
2017-07-11 20:56:44.795398 W | mvcc/backend: snapshotting is taking more than 30.000114844 seconds to finish transferring 0.10256410256410256 MB [started at 2017-07-11 20:56:14.794637631 +0800 CST]
2017-07-11 20:57:14.794814 W | mvcc/backend: snapshotting is taking more than 60.000140182 seconds to finish transferring 0.10256410256410256 MB [started at 2017-07-11 20:56:14.794637631 +0800 CST]
2017-07-11 20:57:44.794820 W | mvcc/backend: snapshotting is taking more than 90.000153091 seconds to finish transferring 0.10256410256410256 MB [started at 2017-07-11 20:56:14.794637631 +0800 CST]
2017-07-11 20:58:14.794832 W | mvcc/backend: snapshotting is taking more than 120.000159895 seconds to finish transferring 0.10256410256410256 MB [started at 2017-07-11 20:56:14.794637631 +0800 CST]
2017-07-11 20:58:44.794778 W | mvcc/backend: snapshotting is taking more than 150.000109395 seconds to finish transferring 0.10256410256410256 MB [started at 2017-07-11 20:56:14.794637631 +0800 CST]
2017-07-11 20:58:59.895894 W | rafthttp: database snapshot [index: 219988768, to: 97ce2299e37ebb20] failed to be sent out (unexpected http status Bad Request while posting to "http://11.131.105.212:2280/raft/snapshot")
2017-07-11 20:58:59.895931 E | rafthttp: failed to post 97ce2299e37ebb20 on sendMsgSnap (unexpected http status Bad Request while posting to "http://11.131.105.212:2280/raft/snapshot")
2017-07-11 20:58:59.895940 I | rafthttp: peer 97ce2299e37ebb20 became inactive
2017-07-11 20:58:59.895982 W | etcdserver: failed to write database snapshot out [written bytes: 0]: meta 0 copy: io: read/write on closed pipe
2017-07-11 20:59:11.046790 I | etcdserver/api/v3rpc: grpc: Server.processUnaryRPC failed to write status: stream error: code = DeadlineExceeded desc = "context deadline exceeded"

**Comment by yanlinly** [comment]
i want to low "snapshot-count"  to release memory.  but use more memory.
![image](https://user-images.githubusercontent.com/17695352/28071211-de9e670e-6681-11e7-9709-ad1542aaa165.png)

**Comment by yanlinly** [comment]
I found snapshot tuning,memory up quickly.  I worry the node dead.  I don't know the memory use and gc rule.  you have infomation?
